window.sectionsData = [
  {
    id: "obj01",
    title: "Objective: Discover the 46th Room",
    color: "blue",
    dependencies: [],
    information: [],
    checkboxes: ["obj01_1_room46"],
  },
  {
    id: "obj04",
    title: "Objective: Solve the Chess Puzzle",
    color: "blue",
    dependencies: ["TK"],
    information: [],
    checkboxes: [
      "obj04_002_entrance",
      "obj04_003_spareroom",
      "obj04_005_parlor",
      "obj04_006_billiardroom",
      "obj04_009_closet",
      "obj04_012_storeroom",
      "obj04_013_nook",
      "obj04_017_den",
      "obj04_021_pantry",
      "obj04_031_utility_closet",
      "obj04_034_security",
      "obj04_042_observatory",
      "obj04_047_bedroom",
      "obj04_048_boudoir",
      "obj04_049_guestbedroom",
      "obj04_055_hallway",
      "obj04_056_westwinghall",
      "obj04_058_corridor",
      "obj04_065_courtyard",
      "obj04_071_commissary",
      "obj04_072_kitchen",
      "obj04_079_lavatory",
      "obj04_080_chapel",
      "obj04_081_maidschamber",
    ]
  },
  {
    id: "obj03",
    title: "Objective: Solve the Paintings Puzzle",
    color: "blue",
    dependencies: ["TK"],
    information: [],
    checkboxes: [
      "obj03_r6f4",
      "obj03_r5f4",
      "obj03_r5f5",
      "obj03_r4f1",
      "obj03_r4f2",
      "obj03_r4f3",
      "obj03_r4f4",
      "obj03_r4f5",
      "obj03_r3f1",
      "obj03_r3f2",
      "obj03_r3f3",
      "obj03_r3f4",
      "obj03_r3f5",
      "obj03_r2f2",
      "obj03_r2f3",
      "obj03_r2f4",
      "obj03_r2f5",
      "obj03_r1f1",
      "obj03_r1f2",
      "obj03_r1f3",
      "obj03_r1f4",
      "obj03_r1f5",
    ]
  },
  {
    id: "obj02",
    title: "Objective: Complete the Mount Holly Directory",
    color: "blue",
    mysteryType: "room",
    dependencies: [],
    information: [],
    checkboxes: [
      "obj02_003_spareroom",
      "obj02_005_parlor",
      "obj02_006_billiardroom",
      "obj02_009_closet",
      "obj02_012_storeroom",
      "obj02_013_nook",
      "obj02_017_den",
      "obj02_021_pantry",
      "obj02_031_utilitycloset",
      "obj02_034_security",
      "obj02_042_observatory",
      "obj02_045_antechamber",
      "obj02_046_room46",
      "obj02_047_bedroom",
      "obj02_048_boudoir",
      "obj02_049_guestbedroom",
      "obj02_055_hallway",
      "obj02_056_westwinghall",
      "obj02_058_corridor",
      "obj02_065_courtyard",
      "obj02_071_commissary",
      "obj02_072_kitchen",
      "obj02_079_lavatory",
      "obj02_080_chapel",
      "obj02_081_maidschamber",
    ]
  },
  {
    id: "obj05",
    title: "Objective: Discover All the Items",
    color: "blue",
    mysteryType: "item",
    dependencies: [],
    information: [],
    checkboxes: [
      "obj05_01_sledgehammer",
      "obj05_02_coinpurse",
      "obj05_03_windupkey",
      "obj05_04_saltshaker",
    ]
  },
  {
    id: "obj06",
    title: "Objective: Activate All the Constellations",
    color: "blue",
    mysteryType: "item",
    dependencies: ["dir042_telescope"],
    information: [],
    checkboxes: [
      "obj06_001_northstar",
      "obj06_002_thetwins",
      "obj06_003_theslice",
      "obj06_004_diamondusminor",
      "obj06_005_thesoutherncross",
      "obj06_007_farmersapple",
      "obj06_008_clavisthekey",
      "obj06_011_diamondusmajor",
      "obj06_012_draxusthedead",
      "obj06_015_thesail",
      "obj06_020_florealisbloomofthesky",
    ]
  },
  {
    id: "info_house",
    title: "Mount Holly Directory",
    color: "blue",
    dependencies: [],
    subsections: [
      {
        id: "dir002",
        title: "002: Entrance Hall",
        color: "blue",
        dependencies: [],
        information: ["dir002_description", "dir002_info"],
        checkboxes: ["dir002_item_blueprint", "dir002_note_letter1", "dir002_note_black", "dir002_person1", "dir002_person2", "dir002_search"],
      },
      {
        id: "dir003",
        title: "003: Spare Room",
        color: "blue",
        dependencies: ["obj02_003_spareroom"],
        information: ["dir003_description"],
        checkboxes: ["dir003_search"],
      },
      {
        id: "dir005",
        title: "005: Parlor",
        color: "blue",
        dependencies: ["obj02_005_parlor"],
        information: ["dir005_description", "dir005_info", "dir005_chess"],
        checkboxes: ["obj05_03_windupkey", "dir005_note_letter", "dir005_search"],
      },
      {
        id: "dir006",
        title: "006: Billiard Room",
        color: "blue",
        dependencies: ["obj02_006_billiardroom"],
        information: ["dir006_description", "dir006_info"],
        checkboxes: ["dir006_search"],
      },
      {
        id: "dir009",
        title: "009: Closet",
        color: "blue",
        dependencies: ["obj02_009_closet"],
        information: ["dir009_description", "dir009_info"],
        checkboxes: ["dir009_search"],
      },
      {
        id: "dir012",
        title: "012: Storeroom",
        color: "blue",
        dependencies: ["obj02_012_storeroom"],
        information: ["dir012_description", "dir012_info", "dir012_chess"],
        checkboxes: ["dir012_search", "dir012_drawing_identify"],
      },
      {
        id: "dir013",
        title: "013: Nook",
        color: "blue",
        dependencies: ["obj02_013_nook"],
        information: ["dir013_description", "dir013_chess"],
        checkboxes: ["dir013_note", "dir013_search"],
      },
      {
        id: "dir017",
        title: "017: Den",
        color: "blue",
        dependencies: ["obj02_017_den"],
        information: ["dir017_description", "dir017_chess"],
        checkboxes: ["dir017_search"],
      },
      {
        id: "dir021",
        title: "021: Pantry",
        color: "blue",
        dependencies: ["obj02_021_pantry"],
        information: ["dir021_description"],
        checkboxes: ["dir021_note", "dir021_search"],
      },
      {
        id: "dir031",
        title: "031: Utility Closet",
        color: "blue",
        dependencies: ["obj02_031_utilitycloset"],
        information: ["dir031_description", "dir031_info"],
        checkboxes: ["dir031_search", "dir031_vac", "dir031_switch"],
      },
      {
        id: "dir034",
        title: "034: Security",
        color: "blue",
        dependencies: ["obj02_034_security"],
        information: ["dir034_description", "dir034_info", "dir034_chess"],
        checkboxes: ["dir034_note_pad", "dir034_note_notice", "dir034_note_red", "dir034_note_blue", "obj_network_unlock", "dir034_search"],
      },
      {
        id: "dir042",
        title: "042: Observatory",
        color: "blue",
        dependencies: ["obj02_042_observatory"],
        information: ["dir042_description", "dir042_chess"],
        checkboxes: ["dir042_note_book", "dir042_telescope", "dir042_search"],
      },
      {
        id: "dir045",
        title: "045: Antechamber",
        color: "blue",
        dependencies: ["obj02_045_antechamber"],
        information: ["dir045_description", "dir045_info"],
        checkboxes: [],
      },
      {
        id: "dir046",
        title: "046: Room 46",
        color: "blue",
        dependencies: ["obj02_046_room46"],
        information: ["dir046_description", "dir046_info"],
        checkboxes: [],
      },
      {
        id: "dir047",
        title: "047: Bedroom",
        color: "purple",
        dependencies: ["obj02_047_bedroom"],
        information: ["dir047_description", "dir047_info", "dir047_chess"],
        checkboxes: ["dir047_note_postcard", "dir047_photo", "dir047_photo_identify", "dir047_finger", "dir047_search"],
      },
      {
        id: "dir048",
        title: "048: Boudoir",
        color: "purple",
        dependencies: ["obj02_048_boudoir"],
        information: ["dir048_description"],
        checkboxes: ["dir048_note", "dir048_search"],
      },
      {
        id: "dir049",
        title: "049: Guest Bedroom",
        color: "purple",
        dependencies: ["obj02_049_guestbedroom"],
        information: ["dir049_description", "dir049_info", "dir049_chess"],
        checkboxes: ["dir049_note", "dir049_search"],
      },
      {
        id: "dir055",
        title: "055: Hallway",
        color: "orange",
        dependencies: ["obj02_055_hallway"],
        information: ["dir055_description"],
        checkboxes: ["dir055_note_red", "dir055_search"],
      },
      {
        id: "dir056",
        title: "056: West Wing Hall",
        color: "orange",
        dependencies: ["obj02_056_westwinghall"],
        information: ["dir056_description"],
        checkboxes: ["dir056_note", "dir056_search"],
      },
      {
        id: "dir058",
        title: "058: Corridor",
        color: "orange",
        dependencies: ["obj02_058_corridor"],
        information: ["dir058_description"],
        checkboxes: ["dir058_search"],
      },
      {
        id: "dir065",
        title: "065: Courtyard",
        color: "green",
        dependencies: ["obj02_065_courtyard"],
        information: ["dir065_description"],
        checkboxes: ["dir065_search"],
      },
      {
        id: "dir071",
        title: "071: Commissary",
        color: "gold",
        dependencies: ["obj02_071_commissary"],
        information: ["dir071_description"],
        checkboxes: ["dir071_note_flyer", "dir034_note_notice", "dir071_note_red", "dir071_search"],
      },
      {
        id: "dir072",
        title: "072: Kitchen",
        color: "gold",
        dependencies: ["obj02_072_kitchen"],
        information: ["dir072_description"],
        checkboxes: ["dir072_search"],
      },
      {
        id: "dir079",
        title: "079: Lavatory",
        color: "red",
        dependencies: ["obj02_079_lavatory"],
        information: ["dir079_description", "dir079_info"],
        checkboxes: ["dir079_search"],
      },
      {
        id: "dir080",
        title: "080: Chapel",
        color: "red",
        dependencies: ["obj02_080_chapel"],
        information: ["dir080_description", "dir080_info"],
        checkboxes: ["dir080_search", "dir080_angel1", "dir080_angel2", "dir080_angel3", "dir080_angel4", "dir080_angel5", "dir080_angel6", "dir080_angel7"],
      },
      {
        id: "dir081",
        title: "081: Maid's Chamber",
        color: "red",
        dependencies: ["obj02_081_maidschamber"],
        information: ["dir081_description"],
        checkboxes: ["dir081_note_notice", "dir081_note_photo", "dir081_search"],
      },
    ],
  },
  {
    id: "info_items",
    title: "Items",
    color: "blue",
    dependencies: [],
    information: [
      "item01_sledgehammer",
      "item02_coinpurse",
      "item03_windupkey",
      "item04_saltshaker",
    ],
  },
  {
    id: "info_people",
    title: "Who's Who?",
    color: "blue",
    dependencies: [],
    subsections: [
      {
        id: "person01_herbie",
        title: "Baron Herbert S. Sinclair",
        color: "blue",
        dependencies: [],
        information: ["person01_herbie_001"],
        checkboxes: [],
      },
      {
        id: "person06_clara",
        title: "Lady Clara Epsen",
        color: "blue",
        optionalDependencies: true,
        dependencies: ["dir056_note"],
        information: ["person06_clara_001"],
        checkboxes: [],
      },
      {
        id: "person02_baroness",
        title: "Baroness Auravei Sinclair",
        color: "blue",
        optionalDependencies: true,
        dependencies: ["dir047_photo_identify"],
        information: ["person02_baroness_001"],
        checkboxes: [],
      },
      {
        id: "person03_babbage",
        title: "House Manager Mrs. Babbage",
        color: "blue",
        optionalDependencies: true,
        dependencies: ["dir034_note_notice"],
        information: ["person03_babbage_001"],
        checkboxes: [],
      },
      {
        id: "person04_bridgette",
        title: "Maid Bridgette",
        color: "blue",
        optionalDependencies: true,
        dependencies: ["dir021_note"],
        information: ["person04_bridgette_001"],
        checkboxes: [],
      },
      {
        id: "person05_richardwitt",
        title: "Author Richard Witt",
        color: "blue",
        optionalDependencies: true,
        dependencies: ["dir042_note_book"],
        information: ["person05_richardwitt_001"],
        checkboxes: [],
      },
    ],
  },
  {
    id: "info_timeline",
    title: "The Timeline",
    color: "blue",
    dependencies: [],
    information: [
      "date002", // 1809
      "date003", // 1983-06-15
      "date001", // 1993-03-18
      "date004", // 1993-11-06
    ],
    checkboxes: [],
  },
  {
    id: "info_notes",
    title: "Letters & Notes",
    color: "blue",
    dependencies: [],
    subsections: [
      {
        id: "info_notes_books",
        title: "Books",
        color: "blue",
        optionalDependencies: true,
        dependencies: ["dir042_note_book"],
        information: [
          "note016", // 042 - observatory
        ],
      },
      {
        id: "info_notes_letters",
        title: "Letters",
        color: "blue",
        dependencies: ["dir002_note_letter1"],
        information: [
          "note002", // 002 - entrance hall
          "note006", // 005 - parlor
          "note017", // 049 - guest bedroom
        ],
      },
      {
        id: "info_notes_cards",
        title: "Note Cards",
        color: "blue",
        dependencies: [],
        information: [
          "note001", // opening cinematic
          "note003", // 002 - entrance hall
          "note005", // 012 - storeroom
          "note015", // 013 - nook
          "note007", // 021 - pantry
          "note008", // 034 - security
          "note009", // 034 - security
          "note010", // 034 - security
          "note011", // 034 - security
          "note012", // 047 - bedroom
          "note019", // 047 - bedroom
          "note004", // 055 - hallway
          "note018", // 056 - west wing hall
          "note013", // 071 - commissary
          "note014", // 071 - commissary
          "note020", // 081 - maid's chamber
          "note021", // 081 - maid's chamber
        ],
      },
    ],
  },
];
